Mesquite: Fix warnings from cdash builds (#634)
Fixed all warnings from cdash builds.

One warning stops triggering with these changes:
error: ‘Mesquite2::barrier_violated_msg’ defined but not used

However it's not clear why this was triggered originally
and why it stops triggering now. This commit does not
directly act to fix that warning.

Switching to release I noted one error (not fixed) which
triggers for: testSuite/idft_time/main.cpp

An array out of bounds is indicated for
Mesquite_SymMatrix3D.hpp line 96.
That may be a logical error with the test setup.